# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
            /usr/lib/local/node_modules/
          key: ${{ runner.os }}-cache

      # Buld the code and publish it to github
      - name: Install Required Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Install Angular Cli
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo npm install -g @angular/cli angular-cli-ghpages

      - name: Build Packages.
        run: sudo ng build --prod --base-href https://$GITHUB_ACTOR.github.io/angular-basics/

      - name: Publish code
        run: sudo ngh --no-silent --name $GITHUB_ACTOR
